FROM amd64/python:3.7-slim-buster

# ruuvitag dependencies.
RUN apt-get update \
    && apt-get -y install bluetooth bluez bluez-hcidump sudo

WORKDIR /app

RUN pip install ptvsd==4.1.3
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY app .

# For demo purposes, started as root to make sure 
# there are no permission issues.
USER root

CMD [ "python3", "-u", "./main.py" ]